const rankList = {
    1: {
        ja: 'アンランク1',
        en: 'Unranked1',
        url: '/img/rank/1',
        img: './img/rank/unranked.png',
    },
    2: {
        ja: 'アンランク2',
        en: 'Unranked2',
        url: '/img/rank/2',
        img: './img/rank/unranked.png',
    },
    3: {
        ja: 'アイアン1',
        en: 'Iron 1',
        url: '/img/rank/3',
        img: './img/rank/Iron_1_Rank.png',
    },
    4: {
        ja: 'アイアン2',
        en: 'Iron 2',
        url: '/img/rank/4',
        img: './img/rank/Iron_2_Rank.png',
    },
    5: {
        ja: 'アイアン3',
        en: 'Iron 3',
        url: '/img/rank/5',
        img: './img/rank/Iron_3_Rank.png',
    },
    6: {
        ja: 'ブロンズ1',
        en: 'Bronze 1',
        url: '/img/rank/6',
        img: './img/rank/Bronze_1_Rank.png',
    },
    7: {
        ja: 'ブロンズ2',
        en: 'Bronze 2',
        url: '/img/rank/7',
        img: './img/rank/Bronze_2_Rank.png',
    },
    8: {
        ja: 'ブロンズ3',
        en: 'Bronze 3',
        url: '/img/rank/8',
        img: './img/rank/Bronze_3_Rank.png',
    },
    9: {
        ja: 'シルバー1',
        en: 'Silver 1',
        url: '/img/rank/9',
        img: './img/rank/Silver_1_Rank.png',
    },
    10: {
        ja: 'シルバー2',
        en: 'Silver 2',
        url: '/img/rank/10',
        img: './img/rank/Silver_2_Rank.png',
    },
    11: {
        ja: 'シルバー3',
        en: 'Silver 3',
        url: '/img/rank/11',
        img: './img/rank/Silver_3_Rank.png',
    },
    12: {
        ja: 'ゴールド1',
        en: 'Gold 1',
        url: '/img/rank/12',
        img: './img/rank/Gold_1_Rank.png',
    },
    13: {
        ja: 'ゴールド2',
        en: 'Gold 2',
        url: '/img/rank/13',
        img: './img/rank/Gold_2_Rank.png',
    },
    14: {
        ja: 'ゴールド3',
        en: 'Gold 3',
        url: '/img/rank/14',
        img: './img/rank/Gold_3_Rank.png',
    },
    15: {
        ja: 'プラチナ1',
        en: 'Platinum 1',
        url: '/img/rank/15',
        img: './img/rank/Platinum_1_Rank.png',
    },
    16: {
        ja: 'プラチナ2',
        en: 'Platinum 2',
        url: '/img/rank/16',
        img: './img/rank/Platinum_2_Rank.png',
    },
    17: {
        ja: 'プラチナ3',
        en: 'Platinum 3',
        url: '/img/rank/17',
        img: './img/rank/Platinum_3_Rank.png',
    },
    18: {
        ja: 'ダイヤ1',
        en: 'Diamond 1',
        url: '/img/rank/18',
        img: './img/rank/Diamond_1_Rank.png',
    },
    19: {
        ja: 'ダイヤ2',
        en: 'Diamond 2',
        url: '/img/rank/19',
        img: './img/rank/Diamond_2_Rank.png',
    },
    20: {
        ja: 'ダイヤ3',
        en: 'Diamond 3',
        url: '/img/rank/20',
        img: './img/rank/Diamond_3_Rank.png',
    },
    21: {
        ja: 'アセンダント1',
        en: 'Ascendant 1',
        url: '/img/rank/21',
        img: './img/rank/Ascendant_1_Rank.png',
    },
    22: {
        ja: 'アセンダント2',
        en: 'Ascendant 2',
        url: '/img/rank/22',
        img: './img/rank/Ascendant_2_Rank.png',
    },
    23: {
        ja: 'アセンダント3',
        en: 'Ascendant 3',
        url: '/img/rank/23',
        img: './img/rank/Ascendant_3_Rank.png',
    },
    24: {
        ja: 'インモータル1',
        en: 'Immortal 1',
        url: '/img/rank/24',
        img: './img/rank/Immortal_1_Rank.png',
    },
    25: {
        ja: 'インモータル2',
        en: 'Immortal 2',
        url: '/img/rank/25',
        img: './img/rank/Immortal_2_Rank.png',
    },
    26: {
        ja: 'インモータル3',
        en: 'Immortal 3',
        url: '/img/rank/26',
        img: './img/rank/Immortal_3_Rank.png',
    },
    27: {
        ja: 'レディアント',
        en: 'Radiant',
        url: '/img/rank/27',
        img: './img/rank/Radiant_Rank.png',
    }
}

module.exports = rankList;